### ISSUE TITLE
NPM warning for npmrc entry

### ISSUE THREAD

**Issue by wallzero** [flathub/org.freedesktop.Sdk.Extension.node18#27]
When using NPM I receive the following warning:

```
npm WARN config tmp This setting is no longer used.  npm stores temporary files in a special
npm WARN config location in the cache, and they are managed by
npm WARN config     [`cacache`](http://npm.im/cacache).
```

It is possible to remove the `tmp` line from `~/.var/app/com.vscodium.codium/config/npmrc` but not from the Flatpak's read-only `/app/etc/npmrc`.

The warning [does cause some issues](https://github.com/commitizen/cz-cli/issues/964) with command line utilities executed by `npm`. Would it be possible to remove the line in thie Flatpak's `/app/etc/npmrc` or is this an upstream issue?

**Comment by gasinvein** [comment]
In what app did you find `/app/etc/npmrc`?

**Comment by wallzero** [comment]
`com.vscodium.codium` but I thought `/app/etc/npmrc` was placed by using `FLATPAK_ENABLE_SDK_EXT=node18`. Is that wrong?

**Comment by gasinvein** [comment]
`FLATPAK_ENABLE_SDK_EXT=node18` env var is evaluated by the wrapper at run time and it can't add files to `/app` or `/usr`. And `/app/etc/npmrc` really shouldn't be there.

**Comment by wallzero** [comment]
Understood. [I think I found the culprit too](https://github.com/flathub/com.vscodium.codium/blob/master/npmrc). Thanks!
