### ISSUE TITLE
Flatpak build with extension failing: "npm: command not found"

### ISSUE THREAD

**Issue by Zishan-Rahman** [flathub/org.freedesktop.Sdk.Extension.node18#40]
I have a PR open, flathub/com.wickeditor.WickEditor#2, in which I'm trying to update the Freedesktop runtime used in the Wick Editor, from 22.08 to 23.08. Currently it uses the [org.freedesktop.Sdk.Extension.node14](https://github.com/flathub/org.freedesktop.Sdk.Extension.node14) extension, which doesn't have a 23.08 branch (yet), and Node.js 14 is EOL. I therefore decided to change the extension to _this_ one, the current LTS version of Node.js, and when I try to build the test Flatpak, [the build fails](https://buildbot.flathub.org/#/builders/6/builds/69194) due to the following error: 

```bash
Running: npm install --offline
FB: Running 'flatpak build --die-with-parent --env=FLATPAK_BUILDER_BUILDDIR=/run/build/WickEditor --nofilesystem=host:reset --filesystem=/srv/buildbot/worker/build-x86_64-2/build/.flatpak-builder/build/WickEditor-1 --bind-mount=/run/build/WickEditor=/srv/buildbot/worker/build-x86_64-2/build/.flatpak-builder/build/WickEditor-1 --build-dir=/run/build/WickEditor/main --bind-mount=/run/ccache=/srv/buildbot/worker/build-x86_64-2/build/.flatpak-builder/ccache --unshare=network --env=SOURCE_DATE_EPOCH=1695842100 '--env=CFLAGS=-O2 -pipe -g -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer ' '--env=CXXFLAGS=-O2 -pipe -g -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer ' '--env=LDFLAGS=-L/app/lib -Wl,-z,relro,-z,now -Wl,--as-needed ' --env=NPM_CONFIG_LOGLEVEL=info --env=npm_config_offline=true --env=npm_config_nodedir=/usr/lib/sdk/node14 --env=npm_config_cache=/run/build/WickEditor/flatpak-node/npm-cache --env=XDG_CACHE_HOME=/run/build/WickEditor/flatpak-node/cache --env=CCACHE_DIR=/run/ccache/disabled --env=PATH=/app/bin:/usr/bin:/usr/lib/sdk/node14/bin --env=LD_LIBRARY_PATH=/app/lib --env=PKG_CONFIG_PATH=/app/lib/pkgconfig:/app/share/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig --env=FLATPAK_BUILDER_N_JOBS=64 /srv/buildbot/worker/build-x86_64-2/build/.flatpak-builder/rofiles/rofiles-xsvCkB /bin/sh -c 'npm install --offline'' on host
/bin/sh: line 1: npm: command not found
FB: host_command_exited_cb 591323 32512
```

I've not had this problem before. I've already updated the Wick Editor Flatpak's runtime once before to 22.08 (flathub/com.wickeditor.WickEditor#1) and the npm command was found and used without further problems, so I don't know what's going wrong _here_. If anyone here can help me or give me advice on this, I'd be very grateful.

**Comment by bbhtt** [comment]
You forgot to change the path of the SDK there, commented. https://github.com/flathub/com.wickeditor.WickEditor/pull/2/files#r1340490900

**Comment by Zishan-Rahman** [comment]
> You forgot to change the path of the SDK there, commented. https://github.com/flathub/com.wickeditor.WickEditor/pull/2/files#r1340490900

Ah, thanks. How silly of me :man_facepalming:

When the test build succeeds I'll close this issue.

**Comment by Zishan-Rahman** [comment]
As of now, [the test build is still failing, but for different reasons](https://buildbot.flathub.org/#/builders/6/builds/69535). Since _this_ problem ("npm: command not found") has been resolved, I'll close this issue.
